#!/bin/sh
#
# Convert an image to PNG format
#
# Prerequisites: ImageMagick
# Arguments: FILENAME
# Accepts: 	png, jpg, jpeg, gif
# Outputs: 	png
#

bash lib-check-image-magick; if [ $? -eq 1 ]; then exit 1; fi

# ================================================
# ==========[ Arguments Validity Check ]==========
# ================================================

if [ "$#" -ne 1 ]; then
	echo "Error: Incorrect number of arguments ($#). Needs to be 1."
	echo "Usage: ${0##*/} FILENAME"
	echo "ie:    ${0##*/} test.png"
	exit 1
fi

filePath=$1

if [ ! -f "$filePath" ]; then
	echo "File ($filePath) not found!"
	exit 1
fi

fileFullName=`echo $filePath|grep -i ".png\|.jpg\|.jpeg\|.gif\|.tiff"`
if [ ! -n "$fileFullName" ] ; then
	echo "File not a valid format (png,jpg,jpeg,gif,tiff)"
	exit 1
fi

# ==========================================
# ==========[ Converting Process ]==========
# ==========================================

echo "File: \t\t"$fileFullName
printf "Converting:\t...."

fileName="${fileFullName%.*}"
fileExt="${fileFullName##*.}"

# 1/3 - The actual conversion
convert "$fileName"".""$fileExt" "$fileName"".png"

# 2/3 - Strip all comments and PNG-metadata-chunks
convert "$fileFullName" -strip "$fileFullName"

# 3/3 - If was not originally PNG - remove the old file
if [ $fileExt != "png" ] ; then
	rm $fileFullName
fi

echo " Done!"
