#!/bin/sh
#
# Downsize all images in directory
#
# Prerequisites: ImageMagick
# Arguments: WIDTH HEIGHT DIRPATH
# Accepts: 	png, jpg, jpeg, gif
# Outputs: 	png
#

bash lib-image-magick-check; if [ $? -eq 1 ]; then exit 1; fi

# ================================================
# ==========[ Arguments Validity Check ]==========
# ================================================

if [ "$#" -ne 3 ]; then
	echo "Error:   Incorrect number of arguments"
	echo "Usage: ${0##*/} WIDTH HEIGHT DIRPATH"
	echo "ie:    ${0##*/} 360 480 ~"
	exit 1
fi\

width=$1
height=$2
dirPath=$3

numRegExp='^[0-9]+$'
if ! [[ $width =~ $numRegExp ]] ; then
   echo "Error: Width is not a valid number" >&2
   exit 1
fi
if ! [[ $height =~ $numRegExp ]] ; then
   echo "Error: Height is not a valid number" >&2
   exit 1
fi
if [ ! -d "$dirPath" ]; then
   echo "Error: Directory path does not exist ($dirPath)" >&2
   exit 1
fi

echo "Resolution:" "$width""x""$height"
echo "Begin Conversion"

# ===================================================
# ==========[ Find num conversions needed ]==========
# ===================================================

numConversions=0
for f in *
do
    fileFullName=`echo $f|grep -i ".png\|.jpg\|.jpeg\|.gif\|.tiff"`
	fileName="${fileFullName%.*}"
	fileExt="${fileFullName##*.}"
	if [ -n "$fileFullName" ] ; then
    	let "numConversions += 1"
    fi
done

# ==================================
# ==========[ Conversion ]==========
# ==================================

curConversion=0
for f in *
do
	let "curConversion += 1"
	echo "[""$curConversion"" / "" $numConversions""]"

	fileFullName=`echo $f|grep -i ".png\|.jpg\|.jpeg\|.gif\|.tiff"`
	fileName="${fileFullName%.*}"
	fileExt="${fileFullName##*.}"
	if [ -n "$fileFullName" ] ; then
		imageResize $width $height $fileFullName
	fi
done

printf "All done!\n\n"
